apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smartscaler-controller-sm
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: smartscaler-controller
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
