apiVersion: autoscale.monitoring.io/v1
kind: SmartScaler
metadata:
  name: integration-scaler
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: integration-svc-depl-autoscaler
  metrics:
    - name: cpu
      promql: |
        avg by (pod) (
          rate(container_cpu_usage_seconds_total{
            namespace="default",
            pod=~"integration-svc-depl-autoscaler.*",
            container!="POD"
          }[1m])
        )
      target: 0.25
      weight: 0.6

    - name: rps
      promql:  |
        sum by (pod) (
          rate(http_server_requests_seconds_count{
            namespace="default",
            application="integration-svc-smart",
            status="200",
            uri="/api/v1/monitor/{number}"
          }[1m])
        )
      target: 0.05
      weight: 0.4

    # - name: queue
    #   promql: avg(integration_queue_length{namespace="default", application="integration-svc-smart"})
    #   target: 10
    #   weight: 0.2
  ewmaAlpha: 0.25
  pid:
    kp: 1
    ki: 0.05
    kd: 0.1
  dynamicThreshold:
    enabled: true
    adjustmentFactor: 0.1
  stabilization:
    scaleUpWindow: 15     # seconds
    scaleDownWindow: 90  # seconds
    cooldown: 30
  minReplicas: 1
  maxReplicas: 5