apiVersion: autoscale.monitoring.io/v1
kind: SmartScaler
metadata:
  name: integration-scaler
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: integration-svc-depl-autoscaler
  metrics:
    - name: cpu
      promql: |
        avg by (pod) (
          rate(container_cpu_usage_seconds_total{namespace="default", pod=~"integration-svc-depl-autoscaler.*", container!="POD"}[1m])
        )
      target: 70.0
      weight: 0.6

    - name: rps
      promql:  |
        sum by (pod) (
          rate(http_server_requests_seconds_count{
            namespace="default",
            application="integration-svc-smart"
          }[1m])
        )
      target: 10.0
      weight: 0.3

    - name: queue
      promql: max(integration_queue_length{namespace="default", application="integration-svc-smart"})
      target: 5
      weight: 0.1
  ewmaAlpha: 0.25
  pid:
    kp: 0.6
    ki: 0.02
    kd: 0.1
  dynamicThreshold:
    enabled: true
    adjustmentFactor: 0.1
  stabilization:
    scaleUpWindow: 20     # seconds
    scaleDownWindow: 180  # seconds — longer for memory (JVM) workloads
    cooldown: 45
  minReplicas: 1
  maxReplicas: 5