spring.application.name=IntegrationService
server.port=9110

# Expose Prometheus endpoint for scraping
management.endpoints.web.exposure.include=prometheus,health,info,metrics

# Set actuator base path (default = /actuator)
management.endpoints.web.base-path=/actuator

# Enable Prometheus metrics export
management.metrics.export.prometheus.enabled=true

# (Optional) Histogram buckets for HTTP latency
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.sla.http.server.requests=100ms,300ms,500ms,1s,3s
